openapi: 3.0.3
info:
  description: Synonym Lookup API
  version: 3.0.3
  title: Synonym Lookup API
  contact:
    email: martineriksson91@hotmail.se

components:
  parameters:
    word:
      in: path
      required: true
      name: word
      description: Used to operate on related synonyms
      schema:
        type: string
  schemas:
    createWord:
      type: object
      properties:
        value:
          type: string
        synonyms:
          type: array
          items:
            type: string
paths:
  /v1/words:
    post:
      operationId: PostWord
      summary: Creates a new word with synonyms or adds to existing word
      tags:
        - Words V1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createWord"
      responses:
        201:
          description: Created result with Location header
          headers:
            Location:
              description: Relative path to newly created word
              schema:
                type: string
                format: url
              example: "/v1/words/test/synonyms"
  /v1/words/{word}/synonyms:
    get:
      operationId: GetSynonyms
      summary: Gets synonyms related to input word
      tags:
        - Synonyms V1
      parameters:
        - $ref: "#/components/parameters/word"
      responses:
        200:
          description: List of synonyms related to input word
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example: ["Warm", "Hot", "Temperate"]